apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
#  labels:
#    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: europe-docker.pkg.dev/prod-rest/test-google-cloud-build/gcb_hello_world:latest
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
            ephemeral-storage: 100Mi
          limits:
            cpu: 300m
            memory: 500Mi
            ephemeral-storage: 200Mi