apiVersion: v1
kind: Service
metadata:
  name: hello-world
#  labels:
#    app: hello-world
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      name: rest
      port: 8080
      targetPort: 8080