timeout: 10s
steps:
# example 1
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-docker.pkg.dev/$PROJECT_ID/rest-api/hello_world:test4', '.' ]
images:
  - 'europe-docker.pkg.dev/$PROJECT_ID/rest-api/hello_world:test4'

# example 2
#  - name: "alpine"
#    args: ['echo', '$_TEST_ENV']
#substitutions:
#  _TEST_ENV: Hello World from Alpine STEP in Google Cloud Build.


