#timeout: 20s
substitutions:
  _REGION: 'europe-docker.pkg.dev'

steps:
# example 1
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_REGION}/${PROJECT_ID}/rest-api/hello_world:$SHORT_SHA', '.' ]
images:
  - '${_REGION}/${PROJECT_ID}/rest-api/hello_world:$SHORT_SHA'

# example 2
#  - name: "alpine"
#    args: ['echo', '$_TEST_ENV']
#substitutions:
#  _TEST_ENV: Hello World from Alpine STEP in Google Cloud Build.


