timeout: 120s
substitutions:
  _REGION: 'europe-docker.pkg.dev'

steps:
# example 1
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_REGION}/$PROJECT_ID/rest-api/hello_world:latest || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', '${_REGION}/${PROJECT_ID}/rest-api/hello_world:$SHORT_SHA',
            '-t', '${_REGION}/${PROJECT_ID}/rest-api/hello_world:latest',
            '--cache-from', '${_REGION}/${PROJECT_ID}/rest-api/hello_world:latest',

            '.' ]

images:
  - '${_REGION}/${PROJECT_ID}/rest-api/hello_world:$SHORT_SHA'
  - '${_REGION}/${PROJECT_ID}/rest-api/hello_world:latest'

# example 2
#  - name: "alpine"
#    args: ['echo', '$_TEST_ENV']
#substitutions:
#  _TEST_ENV: Hello World from Alpine STEP in Google Cloud Build.


